services:
  mongodb:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - dev_mongo_data:/data/db
      - ../../../mongo/init/dev:/docker-entrypoint-initdb.d
    networks:
      - team-work
      - dbs
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  mysql:
    image: mysql:8.0
    networks:
      - team-work
      - dbs
    ports:
      - "3307:3306"
    volumes:
      - dev_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: unless-stopped
    ports:
      - "8031:80"
    networks:
      - dbs
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  redis:
    image: redis:8.4-alpine
    networks:
      - dbs
      - team-work
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: apache/kafka:latest
    working_dir: /opt/kafka/bin
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9093:9092"
    networks:
      - team-work
    healthcheck:
      test: [ "CMD-SHELL", "./kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 10s

  teamwork-app:
    image: mordiniaa/teamworkmon
    networks:
      - team-work
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
          condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    volumes:
      - ./admin_password.txt:/run/secrets/admin_password:ro
      - dev_data:/data
    ports:
      - "8081:8080"
    environment:
      PROFILE: dev
      BANNED_IPS_FILE: ${BANNED_IPS_FILE}
      STORAGE_ROOT: ${STORAGE_ROOT}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KAFKA_BS_SERVER: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
      PROFILE_IMAGES_ROOT: ${PROFILE_IMAGES_ROOT}
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_DB_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

networks:
  team-work:
    driver: bridge
  dbs:
    driver: bridge

volumes:
  dev_mongo_data:
  dev_mysql_data:
  dev_data: