apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: "TCP"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-config
          secret:
            secretName: redis-config
      containers:
        - name: redis-container
          image: redis:8.4-alpine
          ports:
            - containerPort: 6379
              protocol: "TCP"
          volumeMounts:
            - mountPath: /usr/local/etc/redis
              name: redis-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: redis-secret
            - name: REDIS_USER
              valueFrom:
                configMapKeyRef:
                  key: REDIS_USER
                  name: redis-store-env
          command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h localhost --user $REDIS_USER -a $REDIS_PASSWORD ping | grep PONG"
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h localhost --user redis-admin -a $REDIS_PASSWORD ping | grep PONG"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "redis-cli -h localhost --user redis-admin -a $REDIS_PASSWORD ping | grep PONG"
            initialDelaySeconds: 30
            periodSeconds: 10