spring:
  application:
    name: backend
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      jedis:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3s
      username: ${REDIS_USER:}
      password: ${REDIS_PASSWORD:}
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB_NAME:team-work}
      username: ${MONGO_DB_USERNAME:team-work}
      password: ${MONGODB_PASSWORD:secretPass}
      authentication-database: ${MONGO_DB_NAME:team-work}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_DB_PORT:3306}/${MYSQL_DATABASE:team-work}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  flyway:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_DB_PORT:3306}/${MYSQL_DATABASE:team-work}
    locations: classpath:db/migration
    schemas: ${MYSQL_DATABASE:team-work}
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: ${KAFKA_BS_SERVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 5000
        request.timeout.ms: 3000
        retries: 2
        max.block.ms: 2000
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topics:
      audit:
        name: prod-audit-topic
        group-name: prod-audit-group
logging:
  level:
    org:
      springframework:
        security: trace
        boot:
          autoconfigure:
            data:
              redis: debug
    apache:
      kafka:
        clients:
          NetworkClient: error
storage:
  profileImages:
    path: ${PROFILE_IMAGES_ROOT:./profile_images_storage}
    mimeTypes:
      - image/jpeg
      - image/png
    profileWidth: 512
    profileHeight: 512
    defaultImageKey: defaultProfileImage
    defaultImagePath: static/images/defaultProfileImage.png
  cloudStorage:
    path: ${STORAGE_ROOT:./files_storage}
  bannedIps:
    path: ${BANNED_IPS_FILE:./banned_ips.txt}

security:
  app:
    jwt:
      token-name: TEAMWORK-ACCESS
      issuer: teamwork-backend
      audience: teamwork-frontend
      secret: ${JWT_SECRET}
      minutes-of-life: 15
    refresh-token:
      token-name: TEAMWORK-REFRESH
      validity-days: 30
    refresh-token-family:
      max-session-days: 90

redis:
  keys:
    session: session
    blocked-ip: blocked_ip
    ban-count: ban_count