spring:
  application:
    name: backend
  output:
    ansi:
      enabled: always
  data:
    redis:
      host: localhost
      port: 6381
      jedis:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 3s
      username: redis-tester
      password: password
    mongodb:
      host: localhost
      port: 27019
      database: team-work
      username: team-work-tester
      password: password
      authentication-database: team-work
  datasource:
    url: jdbc:mysql://localhost:3308/team-work
    username: team-work-tester
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  flyway:
    user: team-work-tester
    password: password
    url: jdbc:mysql://localhost:3308/team-work
    locations: classpath:db/migration
    schemas: team-work
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 5000
        request.timeout.ms: 3000
        retries: 2
        max.block.ms: 2000
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topics:
      audit:
        name: test-audit-topic
        group-name: test-audit-group
logging:
  level:
    org:
      springframework:
        security: trace
        boot:
          autoconfigure:
            data:
              redis: debug
      apache:
        kafka:
          clients:
            NetworkClient: error
storage:
  profileImages:
    path: ./profile_images_storage
    mimeTypes:
      - image/jpeg
      - image/png
    profileWidth: 512
    profileHeight: 512
    defaultImageKey: defaultProfileImage
    defaultImagePath: static/images/defaultProfileImage.png
  cloudStorage:
    path: ./files_storage
  bannedIps:
    path: ./banned_ips.txt

security:
  app:
    jwt:
      token-name: TEAMWORK-ACCESS
      issuer: teamwork-backend
      audience: teamwork-frontend
      secret: testSecret1dkWhat1amwr1t1ngDrinkMilkBeHealthy
      minutes-of-life: 15
    refresh-token:
      token-name: TEAMWORK-REFRESH
      validity-days: 30
    refresh-token-family:
      max-session-days: 90

redis:
  keys:
    session: session
    blocked-ip: blocked_ip
    ban-count: ban_count

server:
  port: 8082