apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mongo/mongo-master.yml
  - mysql/mysql-master.yml
  - redis/redis-master.yml
configMapGenerator:
  - name: mongo-init
    files:
      - ./mongo/init/prod/01-users.js
      - ./mongo/init/prod/02-collections.js
      - ./mongo/init/prod/03-indexes.js
  - name: mongo-store-env
    envs:
      - mongo/env/.env.public
  - name: mysql-store-env
    envs:
      - mysql/env/.env.public
  - name: redis-store-env
    envs:
      - redis/env/.env.public
secretGenerator:
  - name: mongo-secret
    envs:
      - mongo/env/.env.secret
  - name: mysql-secret
    envs:
      - mysql/env/.env.secret
  - name: redis-config
    files:
      - redis/config/redis.conf
  - name: redis-secret
    envs:
      - redis/env/.env.private
